const GREEN_HUE = '60deg';
const DARK_GREEN_HUE = '100deg';
const BROWN_HUE = '350deg';
const RED_HUE = '320deg';
const YELLOW_HUE = '30deg';
const PURPLE_HUE = '240deg';
const BLUE_HUE = '160deg';
const LIGHT_BLUE_HUE = '130deg';
const DARK_BLUE_HUE = '190deg';
const NO_HUE = null;

const ENEMY_DEFS = {
    "Dirty Goblin": {
        name: "Dirty Goblin",
        lootTable: dirtyGoblinLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["Greater Rivertown"],
        loseReps: [],
    },
    "Common Thief": {
        name: "Common Thief",
        lootTable: commonThiefLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["Greater Rivertown"],
        loseReps: [],
    },
    "Mysterious Villain": {
        name: "Mysterious Villain",
        lootTable: mysteriousVillainLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: [],
        loseReps: ["Shadow Army"],
    },
    "Forest Bandit": {
        name: "Forest Bandit",
        lootTable: forestBanditLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["Greater Rivertown"],
        loseReps: [],
    },
    "Creek Hunter": {
        name: "Creek Hunter",
        lootTable: creekHunterLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["Greater Rivertown"],
        loseReps: [],
    },
    "Woods Lurker": {
        name: "Woods Lurker",
        lootTable: woodsLurkerLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: [],
        loseReps: [],
    },
    "Longroad Wild Dog": {
        name: "Longroad Wild Dog",
        lootTable: longroadDogLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: [],
        loseReps: [],
    },
    "Highwayman": {
        name: "Highwayman",
        lootTable: longroadBanditLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: [],
        loseReps: [],
    },
    "Footpad": {
        name: "Footpad",
        lootTable: longroadBanditLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: [],
        loseReps: [],
    },
    "Longroad Alpha Dog": {
        name: "Longroad Alpha Dog",
        lootTable: longroadDogLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: [],
        loseReps: [],
    },
    "Gnoll Gang Road Stalker": {
        name: "Gnoll Gang Road Stalker",
        lootTable: gnollGangsterLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["The Longroad Authority"],
        loseReps: ["Gnoll Gang"],
    },
    "Gnoll Gang Footsoldier": {
        name: "Gnoll Gang Footsoldier",
        lootTable: gnollGangsterLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["The Longroad Authority"],
        loseReps: ["Gnoll Gang"],
    },
    "Gnoll Gang Boss": {
        name: "Gnoll Gang Boss",
        lootTable: gnollGangBossLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["The Longroad Authority"],
        loseReps: ["Gnoll Gang"],
    },
    "Black Magician": {
        name: "Black Magician",
        lootTable: blackMagicianLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: [],
        loseReps: ["Dark Brotherhood"],
    },
    "Soul Unionist": {
        name: "Soul Unionist",
        lootTable: soulUnionistLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: [],
        loseReps: ["Dark Brotherhood"],
    },
    "Dark Brotherhood Commander": {
        name: "Dark Brotherhood Commander",
        lootTable: darkBrotherhoodCommanderLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: [],
        loseReps: ["Dark Brotherhood"],
    },
    "Realm Keeper": {
        name: "Realm Keeper",
        lootTable: spiritRealmThresholdEnemy,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["Farside Visionaries"],
        loseReps: ["Shadow Army"],
    },
    "Shadow Soldier": {
        name: "Shadow Soldier",
        lootTable: spiritRealmThresholdEnemy,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["Farside Visionaries"],
        loseReps: ["Shadow Army"],
    },
    "Death Viewer": {
        name: "Death Viewer",
        lootTable: spiritRealmThresholdEnemy,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["Farside Visionaries"],
        loseReps: ["Shadow Army"],
    },
    "Faraway Scoundrel": {
        name: "Faraway Scoundrel",
        lootTable: farawayScoundrelLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["Faraway Kingdom"],
        loseReps: [],
    },
    "Frozen Invader": {
        name: "Faraway Scoundrel",
        lootTable: frozenInvaderLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["Mountainland Kingdom","Faraway Kingdom","Yetimagic Putrefiers"],
        loseReps: ["Frozen Legion"],
    },
    "Faraway Archvillain": {
        name: "Faraway Archvillain",
        lootTable: farawayArchvillainLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["Faraway Kingdom"],
        loseReps: [],
    },
    "Frozen Lieutenant": {
        name: "Frozen Lieutenant",
        lootTable: frozenLieutenantLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["Mountainland Kingdom","Faraway Kingdom","Yetimagic Putrefiers"],
        loseReps: ["Frozen Legion"],
    },
    "Dirt Dwarf Brute": {
        name: "Dirt Dwarf Brute",
        lootTable: dirtDwarfLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["Mountainland Kingdom"],
        loseReps: ["Dirt Dwarves"],
    },
    "Dirt Dwarf Ambusher": {
        name: "Dirt Dwarf Ambusher",
        lootTable: dirtDwarfLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["Mountainland Kingdom"],
        loseReps: ["Dirt Dwarves"],
    },
    "Fire Cult Sapper": {
        name: "Fire Cult Sapper",
        lootTable: fireCultistLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["Mountainland Kingdom"],
        loseReps: ["Fire Cult"],
    },
    "Fire Cult Slave": {
        name: "Fire Cult Slave",
        lootTable: fireCultSlaveLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["Mountainland Kingdom"],
        loseReps: ["Fire Cult"],
    },
    "Fire Cult Scientist": {
        name: "Fire Cult Scientist",
        lootTable: fireCultistLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["Mountainland Kingdom"],
        loseReps: ["Fire Cult"],
    },
    "Doom Maniac": {
        name: "Doom Maniac",
        lootTable: doomManiacLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: [],
        loseReps: ["Doom Cult"],
    },
    "Living Fire": {
        name: "Living Fire",
        lootTable: livingFireLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["Mountainland Kingdom"],
        loseReps: ["Fire Cult"],
    },
    "Farside Communer": {
        name: "Farside Communer",
        lootTable: farsideCommunerLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["Shadow Army", "Mountainland Kingdom"],
        loseReps: ["Farside Visionaries"],
    },
    "Dark Brotherhood Insider": {
        name: "Dark Brotherhood Insider",
        lootTable: darkBrotherhoodInsiderLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: [],
        loseReps: ["Dark Insider"],
    },
    "Magma Being": {
        name: "Magma Being",
        lootTable: magmaBeingLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: [],
        loseReps: ["Fire Cult"],
    },
    "Disguised Yetimage": {
        name: "Disguised Yetimage",
        lootTable: disguisedYetimageLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["Frozen Legion"],
        loseReps: ["Yetimagic Putrefiers"],
    },
    "Golem Carver": {
        name: "Golem Carver",
        lootTable: golemCarverLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["Mountainland Kingdom"],
        loseReps: [],
    },
    "Mountain King Double-Agent": {
        name: "Mountain King Double-Agent",
        lootTable: mountainKingDoubleAgentLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["Mountainland Kingdom"],
        loseReps: [],
    },
    "Farside Scientist": {
        name: "Farside Scientist",
        lootTable: farsideScientistLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["Shadow Army", "Mountainland Kingdom"],
        loseReps: ["Farside Visionaries"],
    },
    "Farside Officer": {
        name: "Farside Officer",
        lootTable: farsideOfficerLootTable,
        icon: 'defaultEnemy',
        hue: NO_HUE,
        desc: "This is a placeholder description!",
        gainReps: ["Shadow Army", "Mountainland Kingdom"],
        loseReps: ["Farside Visionaries"],
    },
    
};

function spawnEnemy(enemyName, enemyLevel) {
    const template = ENEMY_DEFS[enemyName];
    if (!template) {
        console.error("Unknown enemy: ", enemyName);
        return null;
    }

    return new Entity(
        template.name,
        enemyLevel,
        template.lootTable,
        template.armorClass,
        template.icon,
        template.hue,
        template.desc,
        template.gainReps,
        template.loseReps
    );
}